app = 'yogan-dot-dev'
primary_region = 'ord'
kill_signal = "SIGINT"
kill_timeout = 5
processes = ['app']

[experimental]
auto_rollback = true

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[services]]
protocol = 'tcp'
internal_port = 8080
processes = ['app']

[[services.ports]]
port = 80
handlers = ['http']
force_https = true

[[services.ports]]
port = 443
handlers = ['tls', 'http']

[services.concurrency]
type = 'connections'
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = '15s'
timeout = '2s'
grace_period = '1s'

[[services.http_checks]]
interval = '10s'
timeout = '500ms'
grace_period = '1s'
method = 'get'
path = '/'
protocol = 'http'
tls_skip_verify = false

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
